// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3iUgElIEKHHaYTyUnLnHjYTzqFsGehfI',
    appId: '1:562896721313:web:9a2902d65b2a36425a67e0',
    messagingSenderId: '562896721313',
    projectId: 'alkworkout',
    authDomain: 'alkworkout.firebaseapp.com',
    storageBucket: 'alkworkout.appspot.com',
    measurementId: 'G-P6RGN6ZRG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb22uunLTHS8uAYJcabywKdLwOmPQ2jUE',
    appId: '1:562896721313:android:a1d744438dff93b85a67e0',
    messagingSenderId: '562896721313',
    projectId: 'alkworkout',
    storageBucket: 'alkworkout.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYty8A9eBN6tpxCLao8AfuEJZjutYF_Rg',
    appId: '1:562896721313:ios:10e6fc38a811d2105a67e0',
    messagingSenderId: '562896721313',
    projectId: 'alkworkout',
    storageBucket: 'alkworkout.appspot.com',
    iosBundleId: 'com.example.alkWorkout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYty8A9eBN6tpxCLao8AfuEJZjutYF_Rg',
    appId: '1:562896721313:ios:10e6fc38a811d2105a67e0',
    messagingSenderId: '562896721313',
    projectId: 'alkworkout',
    storageBucket: 'alkworkout.appspot.com',
    iosBundleId: 'com.example.alkWorkout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3iUgElIEKHHaYTyUnLnHjYTzqFsGehfI',
    appId: '1:562896721313:web:11f5503449c322eb5a67e0',
    messagingSenderId: '562896721313',
    projectId: 'alkworkout',
    authDomain: 'alkworkout.firebaseapp.com',
    storageBucket: 'alkworkout.appspot.com',
    measurementId: 'G-6TVYGE8JW2',
  );
}
